-- starter data

INSERT INTO equipment_category (name) VALUES ('10m Wand inkl. Einhausung');
INSERT INTO equipment_category (name) VALUES ('3. Sitzreihe');
INSERT INTO equipment_category (name) VALUES ('48V SGR');
INSERT INTO equipment_category (name) VALUES ('ABS-Prüfstand');
INSERT INTO equipment_category (name) VALUES ('AHV Handlingsgerät');
INSERT INTO equipment_category (name) VALUES ('ATW Einzugsanlage');
INSERT INTO equipment_category (name) VALUES ('Abdrückgabel für Abtriebstulpe');
INSERT INTO equipment_category (name) VALUES ('Abgasabsaugung');
INSERT INTO equipment_category (name) VALUES ('Abgestützte Schraubanlage');
INSERT INTO equipment_category (name) VALUES ('Abgleitkeil Smalloverlap US');
INSERT INTO equipment_category (name) VALUES ('Ablage GLW vorn');
INSERT INTO equipment_category (name) VALUES ('Absaugung MOTEST + Gantry');
INSERT INTO equipment_category (name) VALUES ('Absicherungen');
INSERT INTO equipment_category (name) VALUES ('Absteckwerkzeug für Schwungrad');
INSERT INTO equipment_category (name) VALUES ('Abstützstange HKL');
INSERT INTO equipment_category (name) VALUES ('Adapterkabel für Komponenten-Flash');
INSERT INTO equipment_category (name) VALUES ('Adapterkabel für Türenprüfstand');
INSERT INTO equipment_category (name) VALUES ('Akkuschrauber');
INSERT INTO equipment_category (name) VALUES ('Andrueckhilfe HKL-Dichtung Radien WaRiLos li/re');
INSERT INTO equipment_category (name) VALUES ('Andrückroller Gurney HKL');
INSERT INTO equipment_category (name) VALUES ('Anlage Bremsleitungsbiegen');
INSERT INTO equipment_category (name) VALUES ('Ansteuergerät SHD / PD');
INSERT INTO equipment_category (name) VALUES ('Ansteuergeräte Lenksäule');
INSERT INTO equipment_category (name) VALUES ('Anzeigeverbund Montage Cockpit');
INSERT INTO equipment_category (name) VALUES ('Applikationswerkzeug Diebstahlschutzstern Lenkrad');
INSERT INTO equipment_category (name) VALUES ('Aufdrückwerkzeug Passdaclips');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Aufrüstband');
INSERT INTO equipment_category (name) VALUES ('Autom. ZaZ Prüfung HA');
INSERT INTO equipment_category (name) VALUES ('Batterieeinbau');
INSERT INTO equipment_category (name) VALUES ('Batterierutsche');
INSERT INTO equipment_category (name) VALUES ('Befeuchter Heckemblem');
INSERT INTO equipment_category (name) VALUES ('Befüllung VAG');
INSERT INTO equipment_category (name) VALUES ('Biegeköpfe');
INSERT INTO equipment_category (name) VALUES ('Bolzenschutz A-Säule');
INSERT INTO equipment_category (name) VALUES ('Bremsbefüllanlage');
INSERT INTO equipment_category (name) VALUES ('Bremsdruckprüfung');
INSERT INTO equipment_category (name) VALUES ('Bremsleitungs-Transportwagen');
INSERT INTO equipment_category (name) VALUES ('CCU-Verbau');
INSERT INTO equipment_category (name) VALUES ('Clip Zusatzwasserpumpe');
INSERT INTO equipment_category (name) VALUES ('Crimp-Zangen');
INSERT INTO equipment_category (name) VALUES ('DWZ Bowdenzug');
INSERT INTO equipment_category (name) VALUES ('Demontage Lacktraverse');
INSERT INTO equipment_category (name) VALUES ('Demontage Lacktraverse');
INSERT INTO equipment_category (name) VALUES ('Demontage Montageadapter');
INSERT INTO equipment_category (name) VALUES ('Demontage Montagetraversen');
INSERT INTO equipment_category (name) VALUES ('Diagnose-Interface (I-COM)');
INSERT INTO equipment_category (name) VALUES ('Dichtheitsprüfkabine');
INSERT INTO equipment_category (name) VALUES ('Diodenbremse Spindelantrieb');
INSERT INTO equipment_category (name) VALUES ('Dummy Schliessbuegel HKL-Schloss US');
INSERT INTO equipment_category (name) VALUES ('EC Schrauber');
INSERT INTO equipment_category (name) VALUES ('EC-Schrauber');
INSERT INTO equipment_category (name) VALUES ('EC-Schrauber mit Lübbering Aufsatz (incl. Gyroskopfunktion) für Bremsleitungen');
INSERT INTO equipment_category (name) VALUES ('EH SFV zu FKL');
INSERT INTO equipment_category (name) VALUES ('Einbau MGU');
INSERT INTO equipment_category (name) VALUES ('Einbau Skyroof');
INSERT INTO equipment_category (name) VALUES ('Eindrückwerkezug (lang)');
INSERT INTO equipment_category (name) VALUES ('Eindrückwerkzeug');
INSERT INTO equipment_category (name) VALUES ('Eindrückwerkzeug (kurz)');
INSERT INTO equipment_category (name) VALUES ('Eindrückwerkzeug Spreizniet');
INSERT INTO equipment_category (name) VALUES ('Einfülladapter VAG');
INSERT INTO equipment_category (name) VALUES ('Einpressvorrichtung HEAT Lager I20');
INSERT INTO equipment_category (name) VALUES ('Einrollwerkzeug FKL Dichtung');
INSERT INTO equipment_category (name) VALUES ('Einschlagdorn für Passhülse');
INSERT INTO equipment_category (name) VALUES ('Einstellautomat HLK T1');
INSERT INTO equipment_category (name) VALUES ('Einstellung SHD/PD');
INSERT INTO equipment_category (name) VALUES ('Einstellvorrichtung');
INSERT INTO equipment_category (name) VALUES ('Einstellwerkzeug FKL-Puffer');
INSERT INTO equipment_category (name) VALUES ('Einziehwerkzeug für Passhülsen');
INSERT INTO equipment_category (name) VALUES ('Endoskop');
INSERT INTO equipment_category (name) VALUES ('Ergositz Hatch Coupés/ SACs');
INSERT INTO equipment_category (name) VALUES ('F1-Nacharbeit: CASCADE Prüfstände inkl. Handterminal');
INSERT INTO equipment_category (name) VALUES ('F2-Nacharbeit: CASCADE Prüfstände inkl. Handterminal');
INSERT INTO equipment_category (name) VALUES ('FAS inkl. Lichtteppich + Gantry');
INSERT INTO equipment_category (name) VALUES ('FAS-Prüfstand');
INSERT INTO equipment_category (name) VALUES ('FH Heckklappe');
INSERT INTO equipment_category (name) VALUES ('FH IMC Seitendeckel');
INSERT INTO equipment_category (name) VALUES ('FH PDC');
INSERT INTO equipment_category (name) VALUES ('FH Separierung Gepäckraum');
INSERT INTO equipment_category (name) VALUES ('FH Stirnwand');
INSERT INTO equipment_category (name) VALUES ('Fahrwerk LG/LK - ohne 3-Spindler');
INSERT INTO equipment_category (name) VALUES ('Fahrwerk LU/LK - mit 3-Spindler');
INSERT INTO equipment_category (name) VALUES ('Fixierung FLK');
INSERT INTO equipment_category (name) VALUES ('Fremdbestromungsadapter');
INSERT INTO equipment_category (name) VALUES ('Frontend Anbau');
INSERT INTO equipment_category (name) VALUES ('Fädelhilfe');
INSERT INTO equipment_category (name) VALUES ('Fügehilfe Frontend Anbau');
INSERT INTO equipment_category (name) VALUES ('Fügehilfe Klimaleitung');
INSERT INTO equipment_category (name) VALUES ('Fügehilfe Ring Kondenswasserablaufschlauch');
INSERT INTO equipment_category (name) VALUES ('Fügelhilfe Schelle SCR Dosiermodul');
INSERT INTO equipment_category (name) VALUES ('GPS Dongle');
INSERT INTO equipment_category (name) VALUES ('Gefahrstoffschrank');
INSERT INTO equipment_category (name) VALUES ('Gegenhalter Lenkradverschraubung');
INSERT INTO equipment_category (name) VALUES ('Getriebe Auflegen/ Fügen');
INSERT INTO equipment_category (name) VALUES ('Getriebeölfüllanlagen');
INSERT INTO equipment_category (name) VALUES ('HEAT hinten. Auflegen');
INSERT INTO equipment_category (name) VALUES ('HEAT vorne Auflegen');
INSERT INTO equipment_category (name) VALUES ('HHG Cockpitfügen');
INSERT INTO equipment_category (name) VALUES ('HHG IHKA fügen');
INSERT INTO equipment_category (name) VALUES ('HHG eKMV');
INSERT INTO equipment_category (name) VALUES ('HKL-Gewicht Umlaufteil');
INSERT INTO equipment_category (name) VALUES ('Haltestange HKL Umlaufteil');
INSERT INTO equipment_category (name) VALUES ('Haltevorrichtung für die IB');
INSERT INTO equipment_category (name) VALUES ('Handlingsgeräte für Schrauberabstützung');
INSERT INTO equipment_category (name) VALUES ('Handterminal (ECOS)');
INSERT INTO equipment_category (name) VALUES ('Hebehilfe Schubfeld');
INSERT INTO equipment_category (name) VALUES ('Hebehilfe ZB Träger 1LP');
INSERT INTO equipment_category (name) VALUES ('Heber für Federbeinmontage');
INSERT INTO equipment_category (name) VALUES ('Hintersitze');
INSERT INTO equipment_category (name) VALUES ('Hochvolt Ladesäule');
INSERT INTO equipment_category (name) VALUES ('Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Hochzeit - Projektmanagement und allgemeine Kosten');
INSERT INTO equipment_category (name) VALUES ('Hochzeit - Voraufbau beim Lieferanten');
INSERT INTO equipment_category (name) VALUES ('Hydraulikwägen (Stringo)');
INSERT INTO equipment_category (name) VALUES ('IBS Schutzkappe');
INSERT INTO equipment_category (name) VALUES ('ICOM Tester');
INSERT INTO equipment_category (name) VALUES ('Interaktionsprüfplatz nach Rolle (Kabine, Absaugung, CASCADE)');
INSERT INTO equipment_category (name) VALUES ('KSK Ofen');
INSERT INTO equipment_category (name) VALUES ('Kabelbaum');
INSERT INTO equipment_category (name) VALUES ('Kameraportal');
INSERT INTO equipment_category (name) VALUES ('Kameraportal Airbag Kappen');
INSERT INTO equipment_category (name) VALUES ('Kameraportal Sonnenblenden Label');
INSERT INTO equipment_category (name) VALUES ('Kameraportal WAS');
INSERT INTO equipment_category (name) VALUES ('Kamerasystem Bremsleitungsvarianten');
INSERT INTO equipment_category (name) VALUES ('Kleben Dachantennenhaube');
INSERT INTO equipment_category (name) VALUES ('Kleberapplikation Trägerplatte');
INSERT INTO equipment_category (name) VALUES ('Klebezelle Seitenscheibe');
INSERT INTO equipment_category (name) VALUES ('Kleinwerkzeuge');
INSERT INTO equipment_category (name) VALUES ('Klimadruckprüfung');
INSERT INTO equipment_category (name) VALUES ('Klimafüllanlage');
INSERT INTO equipment_category (name) VALUES ('Kombi-Rolle');
INSERT INTO equipment_category (name) VALUES ('Komponenten-Flash: Kabel');
INSERT INTO equipment_category (name) VALUES ('Komponenten-Flash: Trailer');
INSERT INTO equipment_category (name) VALUES ('Kratzerschutz für Akkuschrauber');
INSERT INTO equipment_category (name) VALUES ('Kühlerfüllanlage');
INSERT INTO equipment_category (name) VALUES ('LAM');
INSERT INTO equipment_category (name) VALUES ('LAM');
INSERT INTO equipment_category (name) VALUES ('ME: Abziehwerkzeug für Schutzkappen');
INSERT INTO equipment_category (name) VALUES ('ME: Aufschiebewerkzeug');
INSERT INTO equipment_category (name) VALUES ('ME: Benetzung und Befettung');
INSERT INTO equipment_category (name) VALUES ('ME: Demontagewerkzeug');
INSERT INTO equipment_category (name) VALUES ('ME: Eindrückwerkzeug');
INSERT INTO equipment_category (name) VALUES ('ME: Entnahme u. Montage Kühlmittelkühler');
INSERT INTO equipment_category (name) VALUES ('ME: SBM für Rückbindung');
INSERT INTO equipment_category (name) VALUES ('ME: Vormontage AGB');
INSERT INTO equipment_category (name) VALUES ('ME: Vormontage AGD');
INSERT INTO equipment_category (name) VALUES ('ME: Vormontage GOEKL');
INSERT INTO equipment_category (name) VALUES ('ME: Vormontage Gummielemente AKMK/AMOEK');
INSERT INTO equipment_category (name) VALUES ('ME: Vormontage SCR KML an Dosiermodul');
INSERT INTO equipment_category (name) VALUES ('ME: Vormontage VKMK/VMOEK (Auffahrschutz)');
INSERT INTO equipment_category (name) VALUES ('MF: Aufschiebewerkzeug Endrohrblende');
INSERT INTO equipment_category (name) VALUES ('MF: Benetzung und Befettung');
INSERT INTO equipment_category (name) VALUES ('MF: Entnahme Abgasanlage');
INSERT INTO equipment_category (name) VALUES ('MF: Entnahme u. Montage DPF/MNK');
INSERT INTO equipment_category (name) VALUES ('MF: Montage Abgasanlage');
INSERT INTO equipment_category (name) VALUES ('MF: Montagehalter Ausrichtung KAT');
INSERT INTO equipment_category (name) VALUES ('MF: Montagezange V-Bandschelle');
INSERT INTO equipment_category (name) VALUES ('MF: Vormontage Druckleitungen');
INSERT INTO equipment_category (name) VALUES ('MN: Anlage für PHEV Tank kleben');
INSERT INTO equipment_category (name) VALUES ('MN: Anlage für Tankdichtheitsprüfung');
INSERT INTO equipment_category (name) VALUES ('MN: Halter für Kraftstoffleitungen');
INSERT INTO equipment_category (name) VALUES ('MN: Meistertanksystem');
INSERT INTO equipment_category (name) VALUES ('MN: Montage Additivtank (SCR u. DWI)');
INSERT INTO equipment_category (name) VALUES ('MN: Montage Kraftstofftank');
INSERT INTO equipment_category (name) VALUES ('MN: Montagehalter Ausrichtung Schlauch-Schelle EFR');
INSERT INTO equipment_category (name) VALUES ('MN: SBM für Rückbindung');
INSERT INTO equipment_category (name) VALUES ('MV FLK zu Seitenwand');
INSERT INTO equipment_category (name) VALUES ('MV FLK zu Stütze Schloss');
INSERT INTO equipment_category (name) VALUES ('MV Flap an STF-Verkleidung/Radhaus li/re');
INSERT INTO equipment_category (name) VALUES ('MV Flaps an Radlaufblende li/re');
INSERT INTO equipment_category (name) VALUES ('MV Fugendichtung Dach');
INSERT INTO equipment_category (name) VALUES ('MV GT-SZ/ BBA-SZ HKL');
INSERT INTO equipment_category (name) VALUES ('MV Gurney HKL');
INSERT INTO equipment_category (name) VALUES ('MV HLK T1 li/re');
INSERT INTO equipment_category (name) VALUES ('MV Heckemblem mit Kamera');
INSERT INTO equipment_category (name) VALUES ('MV Linearpuffer HKL');
INSERT INTO equipment_category (name) VALUES ('MV Modell-SZ HKL');
INSERT INTO equipment_category (name) VALUES ('MV Modell-SZ HKL MPA');
INSERT INTO equipment_category (name) VALUES ('MV SCA-Antrieb in Tailgate');
INSERT INTO equipment_category (name) VALUES ('MV STF-Führung');
INSERT INTO equipment_category (name) VALUES ('MV Scheuerschutzfolie Flap an Radhaus li/re');
INSERT INTO equipment_category (name) VALUES ('MV Scheuerschutzfolie STF-Verkleidung');
INSERT INTO equipment_category (name) VALUES ('MV Schwellerverkleidung HVS');
INSERT INTO equipment_category (name) VALUES ('MV Seitenwand-SZ li/re');
INSERT INTO equipment_category (name) VALUES ('MV Sonder-SZ PHEV/ BEV');
INSERT INTO equipment_category (name) VALUES ('MV Spat an STF-Verkleidung/Radhaus li/re');
INSERT INTO equipment_category (name) VALUES ('MV Verbindung oben hinten');
INSERT INTO equipment_category (name) VALUES ('MV Wischerarm Heckscheibe');
INSERT INTO equipment_category (name) VALUES ('MV Wischermotor Touring');
INSERT INTO equipment_category (name) VALUES ('MV Y-Ausrichtung FRR Sensor');
INSERT INTO equipment_category (name) VALUES ('MV Y-Ausrichtung MRR Sensor');
INSERT INTO equipment_category (name) VALUES ('MV Zierleiste HKL');
INSERT INTO equipment_category (name) VALUES ('MV Zugfeder HKL li/re');
INSERT INTO equipment_category (name) VALUES ('MV xDrive-SZ HKL');
INSERT INTO equipment_category (name) VALUES ('MV xDrive-SZ HKL MPA');
INSERT INTO equipment_category (name) VALUES ('Manuelle ATW Einzugsanlage');
INSERT INTO equipment_category (name) VALUES ('Mess- und Einstellsystem HKL-Durchschlagpuffer');
INSERT INTO equipment_category (name) VALUES ('Messaufnahme Frontend');
INSERT INTO equipment_category (name) VALUES ('Messvorrichtung Dachspoiler Z');
INSERT INTO equipment_category (name) VALUES ('Mixed Position');
INSERT INTO equipment_category (name) VALUES ('Montage Montagetraversen');
INSERT INTO equipment_category (name) VALUES ('Montagegasdämpfer Umlaufteil li/re');
INSERT INTO equipment_category (name) VALUES ('Montagehilfe Airbreather');
INSERT INTO equipment_category (name) VALUES ('Montagehilfe SCA an HKL-Schloss');
INSERT INTO equipment_category (name) VALUES ('Montageschutz (Schweller, I-Tafel, Cockpit)');
INSERT INTO equipment_category (name) VALUES ('Montageschutz Bodenverkleidung');
INSERT INTO equipment_category (name) VALUES ('Montageschutz Cockpit');
INSERT INTO equipment_category (name) VALUES ('Montageschutz Dekor');
INSERT INTO equipment_category (name) VALUES ('Montageschutz HKL-Dichtung STF-Verkleidung');
INSERT INTO equipment_category (name) VALUES ('Montageschutz Mittelkonsole');
INSERT INTO equipment_category (name) VALUES ('Montageschutz Überdrücken HKL');
INSERT INTO equipment_category (name) VALUES ('Motor Auflegen');
INSERT INTO equipment_category (name) VALUES ('Motor LAM');
INSERT INTO equipment_category (name) VALUES ('Motorrollenband');
INSERT INTO equipment_category (name) VALUES ('Multi-Gas Schnüffelgerät');
INSERT INTO equipment_category (name) VALUES ('Nietgeräte');
INSERT INTO equipment_category (name) VALUES ('Nietpistole Bordsteindämpfer');
INSERT INTO equipment_category (name) VALUES ('No Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Non-Generic Equipment');
INSERT INTO equipment_category (name) VALUES ('Notentriegelung HKL-Schloss Umlaufteil');
INSERT INTO equipment_category (name) VALUES ('Notstrategie Dichtungsapplikation');
INSERT INTO equipment_category (name) VALUES ('Notstrategie Frontend Anbau');
INSERT INTO equipment_category (name) VALUES ('Notstrategie SHD / PD Einbau');
INSERT INTO equipment_category (name) VALUES ('Notstrategie Skyroof Einbau');
INSERT INTO equipment_category (name) VALUES ('PAC Man Zange');
INSERT INTO equipment_category (name) VALUES ('PTO Fügen');
INSERT INTO equipment_category (name) VALUES ('Polschutzkappen');
INSERT INTO equipment_category (name) VALUES ('Positionieren Lenkspindel für Hochzeit');
INSERT INTO equipment_category (name) VALUES ('Positioniervorrichtung HKL-Schloss');
INSERT INTO equipment_category (name) VALUES ('Prüfstande A-PPL (A-CAS-Init, A-Data, A-Diag) inkl. Handterminal');
INSERT INTO equipment_category (name) VALUES ('Prüfstande B-PPL (B-Vor, B-Data, B-Diag, EKS-Init, EWS Sync)');
INSERT INTO equipment_category (name) VALUES ('Prüfstände Befüllband (ECOS) inkl. Handterminal');
INSERT INTO equipment_category (name) VALUES ('Prüfstände Befüllband (F1-Diagnose) inkl. FDC');
INSERT INTO equipment_category (name) VALUES ('Prüfstände Befüllband (F1-Init + Infotainment) inkl. FDC');
INSERT INTO equipment_category (name) VALUES ('Prüfstände Befüllband ECOS 12V Adapter (+ Rework+Spare parts)');
INSERT INTO equipment_category (name) VALUES ('Prüfstände Befüllband ECOS USB-Sticks (+ Rework+ Spare parts)');
INSERT INTO equipment_category (name) VALUES ('Prüfstände F2-Diag inkl. FDC');
INSERT INTO equipment_category (name) VALUES ('Prüfstände FDP-Diag');
INSERT INTO equipment_category (name) VALUES ('Prüfstände FH-Init-Rahmenlos');
INSERT INTO equipment_category (name) VALUES ('Prüfstände Key-Init inkl. DGV + NFC');
INSERT INTO equipment_category (name) VALUES ('Prüfstände MOTEST + FINISH (+ FDP-vor-Fahrt) inkl. Scanner');
INSERT INTO equipment_category (name) VALUES ('Prüfvorrichtung Endposition SZL');
INSERT INTO equipment_category (name) VALUES ('RFID Lesestation');
INSERT INTO equipment_category (name) VALUES ('Roboter Cockpitfügen');
INSERT INTO equipment_category (name) VALUES ('Roboter Greifer Cockpitfügen');
INSERT INTO equipment_category (name) VALUES ('Rollen-Prüfstand');
INSERT INTO equipment_category (name) VALUES ('Rollen-Prüfstand (Kombi)');
INSERT INTO equipment_category (name) VALUES ('Rollforming HKL-Dichtung');
INSERT INTO equipment_category (name) VALUES ('Rollforminggeräte Kantenschutz');
INSERT INTO equipment_category (name) VALUES ('SBM Dichtungsapplikation');
INSERT INTO equipment_category (name) VALUES ('SBM Scheibenkleben');
INSERT INTO equipment_category (name) VALUES ('SBM Wisch-/Waschsystem');
INSERT INTO equipment_category (name) VALUES ('SCR Befüllanlage');
INSERT INTO equipment_category (name) VALUES ('SHD/PD');
INSERT INTO equipment_category (name) VALUES ('SHD/PD');
INSERT INTO equipment_category (name) VALUES ('STF-Verkleidung Ladungsträger');
INSERT INTO equipment_category (name) VALUES ('SWKZ Z-Nachstellung SFV');
INSERT INTO equipment_category (name) VALUES ('Scheibenklappe Touring');
INSERT INTO equipment_category (name) VALUES ('Scheibenkleben');
INSERT INTO equipment_category (name) VALUES ('Scheinwerfer');
INSERT INTO equipment_category (name) VALUES ('Scheinwerfereinstelllehre');
INSERT INTO equipment_category (name) VALUES ('Scherenhubtisch');
INSERT INTO equipment_category (name) VALUES ('Schrauberabstützung');
INSERT INTO equipment_category (name) VALUES ('Schutz Schleuderscheibe VTG');
INSERT INTO equipment_category (name) VALUES ('Schäumen');
INSERT INTO equipment_category (name) VALUES ('Seitenschwanschoner');
INSERT INTO equipment_category (name) VALUES ('Seitenschwanschoner Werkzeug');
INSERT INTO equipment_category (name) VALUES ('Separate Hochvoltspeichermontage');
INSERT INTO equipment_category (name) VALUES ('Setzwerkzeug Spreizniet Halteleiste Schweller');
INSERT INTO equipment_category (name) VALUES ('Spur-Sturz-Einstellanlage');
INSERT INTO equipment_category (name) VALUES ('Standard Foliendispenser');
INSERT INTO equipment_category (name) VALUES ('Stanze');
INSERT INTO equipment_category (name) VALUES ('Stanze Innenverkleidung HKL');
INSERT INTO equipment_category (name) VALUES ('Steckwerkzeug');
INSERT INTO equipment_category (name) VALUES ('Stempelhubtisch');
INSERT INTO equipment_category (name) VALUES ('Stirnwandstanzen');
INSERT INTO equipment_category (name) VALUES ('Tablet-PC');
INSERT INTO equipment_category (name) VALUES ('Tailgate Ladungsträger De-/Montage');
INSERT INTO equipment_category (name) VALUES ('Taktiles Messsystem (FARO-Arm)');
INSERT INTO equipment_category (name) VALUES ('Tankanlage');
INSERT INTO equipment_category (name) VALUES ('Türeneinbau');
INSERT INTO equipment_category (name) VALUES ('Türenprüfstand');
INSERT INTO equipment_category (name) VALUES ('Türenprüfstände');
INSERT INTO equipment_category (name) VALUES ('Türenprüfstände');
INSERT INTO equipment_category (name) VALUES ('Türensausbau');
INSERT INTO equipment_category (name) VALUES ('UVM FRR/MRR Sensor an Halter');
INSERT INTO equipment_category (name) VALUES ('UVM Halter LKS');
INSERT INTO equipment_category (name) VALUES ('UVM Halter Lidar');
INSERT INTO equipment_category (name) VALUES ('UVM Luftführung');
INSERT INTO equipment_category (name) VALUES ('UVM Stossabsorber 1LP');
INSERT INTO equipment_category (name) VALUES ('UVM Vorderwand');
INSERT INTO equipment_category (name) VALUES ('UVM ZB Crashsystem');
INSERT INTO equipment_category (name) VALUES ('Umrüstung Flashtrailer auf neues Bordnetz');
INSERT INTO equipment_category (name) VALUES ('VAG Fügen');
INSERT INTO equipment_category (name) VALUES ('VM Blende HKL');
INSERT INTO equipment_category (name) VALUES ('VM DPF B57TÜ2');
INSERT INTO equipment_category (name) VALUES ('VM DWA');
INSERT INTO equipment_category (name) VALUES ('VM DWA-Sirene');
INSERT INTO equipment_category (name) VALUES ('VM FHW');
INSERT INTO equipment_category (name) VALUES ('VM Generator');
INSERT INTO equipment_category (name) VALUES ('VM Griffleiste');
INSERT INTO equipment_category (name) VALUES ('VM HBL in Aeroblade');
INSERT INTO equipment_category (name) VALUES ('VM HBM EC Schrauber (Offenmaul)');
INSERT INTO equipment_category (name) VALUES ('VM HBM inkl. Steurungsabfrage');
INSERT INTO equipment_category (name) VALUES ('VM HEAT');
INSERT INTO equipment_category (name) VALUES ('VM Heckspoiler aktiv');
INSERT INTO equipment_category (name) VALUES ('VM Höhenstandssensor an Querlenker oben');
INSERT INTO equipment_category (name) VALUES ('VM Lambda-Sensor');
INSERT INTO equipment_category (name) VALUES ('VM Lenksäule');
INSERT INTO equipment_category (name) VALUES ('VM Notentriegelung Tailgate');
INSERT INTO equipment_category (name) VALUES ('VM Nox-Sensor');
INSERT INTO equipment_category (name) VALUES ('VM Nox/ PM Sensor');
INSERT INTO equipment_category (name) VALUES ('VM Nutensteine Dachspoiler Z');
INSERT INTO equipment_category (name) VALUES ('VM Platinenstromverteiler');
INSERT INTO equipment_category (name) VALUES ('VM RAM/Booster');
INSERT INTO equipment_category (name) VALUES ('VM SCR Dosiermodul');
INSERT INTO equipment_category (name) VALUES ('VM Smart Opener Adapterplatte');
INSERT INTO equipment_category (name) VALUES ('VM Temperatursensor');
INSERT INTO equipment_category (name) VALUES ('VM Tisch für Luftleitungen an Kompressor');
INSERT INTO equipment_category (name) VALUES ('VM Vorrichtung HBM an Halter');
INSERT INTO equipment_category (name) VALUES ('VM Vorrichtung HSS an QLO');
INSERT INTO equipment_category (name) VALUES ('VM Vorrichtung Luftleitungen an Kompressor');
INSERT INTO equipment_category (name) VALUES ('VM Vorrichtung für die IB');
INSERT INTO equipment_category (name) VALUES ('VM Vorrichtung für die IB');
INSERT INTO equipment_category (name) VALUES ('VM hPAD');
INSERT INTO equipment_category (name) VALUES ('VM mPAD');
INSERT INTO equipment_category (name) VALUES ('VM-Tisch VM Unterfahrschutz');
INSERT INTO equipment_category (name) VALUES ('VTG Auflegen/ Fügen');
INSERT INTO equipment_category (name) VALUES ('Verbau Ladedose vorne');
INSERT INTO equipment_category (name) VALUES ('Verdrehsicherung Schließbügel');
INSERT INTO equipment_category (name) VALUES ('Verfahrgeräte Fensterscheiben');
INSERT INTO equipment_category (name) VALUES ('Verlegen Hochvoltkabel');
INSERT INTO equipment_category (name) VALUES ('Verlegen Ladekabel');
INSERT INTO equipment_category (name) VALUES ('Verlobung');
INSERT INTO equipment_category (name) VALUES ('Verlobung');
INSERT INTO equipment_category (name) VALUES ('Verlobung');
INSERT INTO equipment_category (name) VALUES ('Verlobung');
INSERT INTO equipment_category (name) VALUES ('Verlobung');
INSERT INTO equipment_category (name) VALUES ('Verlobung');
INSERT INTO equipment_category (name) VALUES ('Verriegelungswerkzeug Crimpschelle');
INSERT INTO equipment_category (name) VALUES ('Verriegelungswerkzeug Federbandschelle');
INSERT INTO equipment_category (name) VALUES ('Verschraubung HCR Relais');
INSERT INTO equipment_category (name) VALUES ('Verschraubung Lenkspindel');
INSERT INTO equipment_category (name) VALUES ('Vordersitze');
INSERT INTO equipment_category (name) VALUES ('Voreinstellvorrichtung HLK T1 li/re');
INSERT INTO equipment_category (name) VALUES ('Vorladestation hPad');
INSERT INTO equipment_category (name) VALUES ('Vormontage Ablegeboden');
INSERT INTO equipment_category (name) VALUES ('Vormontage Chiller an Halter');
INSERT INTO equipment_category (name) VALUES ('Vormontage Dekor');
INSERT INTO equipment_category (name) VALUES ('Vormontage Klimaleitung an mKMV');
INSERT INTO equipment_category (name) VALUES ('Vormontage Luftausströmer BFS');
INSERT INTO equipment_category (name) VALUES ('Vormontage Luftausströmer FS');
INSERT INTO equipment_category (name) VALUES ('Vormontage Mittenausströmer');
INSERT INTO equipment_category (name) VALUES ('Vormontage Schloss');
INSERT INTO equipment_category (name) VALUES ('Vormontage Standheizung');
INSERT INTO equipment_category (name) VALUES ('Vormontage eKMV');
INSERT INTO equipment_category (name) VALUES ('Vormontage karosseriefeste Seitenscheibe');
INSERT INTO equipment_category (name) VALUES ('Wandler');
INSERT INTO equipment_category (name) VALUES ('Waschwasserbefüllanlage');
INSERT INTO equipment_category (name) VALUES ('Werkstückgträger Mittelkonsole');
INSERT INTO equipment_category (name) VALUES ('Werkstückträger DPF');
INSERT INTO equipment_category (name) VALUES ('Werkstückträger Frontend');
INSERT INTO equipment_category (name) VALUES ('Werkstückträger Fördertechnik');
INSERT INTO equipment_category (name) VALUES ('Werkzeuge Scheibeneinstellung');
INSERT INTO equipment_category (name) VALUES ('Werkzeugwagen');
INSERT INTO equipment_category (name) VALUES ('Werstückträger Cockpit');
INSERT INTO equipment_category (name) VALUES ('Y-Verschraubung li/re');
INSERT INTO equipment_category (name) VALUES ('Zugseil Niederhalten HKL');
INSERT INTO equipment_category (name) VALUES ('Zweifachschrauber vo Gelenkwelle 35up');
INSERT INTO equipment_category (name) VALUES ('Zweisäulenhebebühne');
INSERT INTO equipment_category (name) VALUES ('allgemeine Cascade-Anlage');
INSERT INTO equipment_category (name) VALUES ('eTHD');
INSERT INTO equipment_category (name) VALUES ('eTHD');
INSERT INTO equipment_category (name) VALUES ('elekt. pneumatische Crimp-Zange FPM Schläuche');
INSERT INTO equipment_category (name) VALUES ('man. ZaZ Prüfung');
INSERT INTO equipment_category (name) VALUES ('Öffnungshilfe FKL');
INSERT INTO equipment_category (name) VALUES ('Öffnungshilfe HKL');
INSERT INTO equipment_category (name) VALUES ('Überkopfabroller');

INSERT INTO position_status (name) VALUES ('Active');
INSERT INTO position_status (name) VALUES ('Deleted');
INSERT INTO position_status (name) VALUES ('Frozen');

INSERT INTO realization_status (name) VALUES ('Already exists in plant 0 for KBBG');
INSERT INTO realization_status (name) VALUES ('Canceled');
INSERT INTO realization_status (name) VALUES ('Created');
INSERT INTO realization_status (name) VALUES ('Final Handover');
INSERT INTO realization_status (name) VALUES ('Final Order Started');
INSERT INTO realization_status (name) VALUES ('Handed over to operator at plant 0 for KBBG');
INSERT INTO realization_status (name) VALUES ('Handed over to operator at target plant for PVL');
INSERT INTO realization_status (name) VALUES ('In Specification');
INSERT INTO realization_status (name) VALUES ('On Hold');
INSERT INTO realization_status (name) VALUES ('Ordered/ In progress at supplier');
INSERT INTO realization_status (name) VALUES ('Tendering');
